-- Migracion: Agregar tabla evaluaciones_crediticias
-- No modifica tablas existentes

CREATE TABLE IF NOT EXISTS `evaluaciones_crediticias` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dni` varchar(15) DEFAULT NULL,
  `cliente` varchar(100) DEFAULT NULL,
  `edad` int(11) DEFAULT NULL,
  `estado_civil` varchar(30) DEFAULT NULL,
  `ocupacion` varchar(100) DEFAULT NULL,
  `direccion` varchar(200) DEFAULT NULL,
  `telefono` varchar(20) DEFAULT NULL,
  `ingreso_mensual` decimal(10,2) DEFAULT NULL,
  `antiguedad_laboral` varchar(50) DEFAULT NULL,
  `monto_solicitado` decimal(10,2) DEFAULT NULL,
  `plazo` int(11) DEFAULT NULL,
  `tipo_credito` varchar(50) DEFAULT NULL,
  `num_deudas_activas` int(11) DEFAULT 0,
  `total_cuotas_mensuales` decimal(10,2) DEFAULT 0.00,
  `tiene_aval` varchar(2) DEFAULT NULL,
  `tiene_garantia` varchar(2) DEFAULT NULL,
  `tipo_garantia` varchar(100) DEFAULT NULL,
  `historial_pagos` varchar(30) DEFAULT NULL,
  `capacidad_pago` decimal(10,2) DEFAULT NULL,
  `nivel_endeudamiento` decimal(5,2) DEFAULT NULL,
  `riesgo_estimado` varchar(30) DEFAULT NULL,
  `score` int(11) DEFAULT NULL,
  `clasificacion` varchar(30) DEFAULT NULL,
  `estado` varchar(50) DEFAULT NULL,
  `analista` varchar(50) DEFAULT NULL,
  `observaciones` text DEFAULT NULL,
  `prediccion_knn` varchar(20) DEFAULT NULL,
  `prediccion_id3` varchar(20) DEFAULT NULL,
  `prediccion_rf` varchar(20) DEFAULT NULL,
  `confianza_ml` decimal(5,2) DEFAULT NULL,
  `recomendacion_ml` text DEFAULT NULL,
  `usado_para_credito` tinyint(1) DEFAULT 0,
  `credito_id` int(11) DEFAULT NULL,
  `fecha_desembolso` datetime DEFAULT NULL,
  `fecha_evaluacion` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_dni` (`dni`),
  KEY `idx_estado` (`estado`),
  KEY `idx_fecha` (`fecha_evaluacion`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
